### ISSUE TITLE
Help regarding CUDA

### ISSUE THREAD

**Issue by Codernob** [sagorbrur/bnlp#28]
I am using the bnwiki doc2vec model. It computes embeddings using CPU. It is taking too much time to compute the document embeddings. How can I make it run on my CUDA enabled GPU?

**Comment by sagorbrur** [comment]
Hi @Codernob 
As per my knowledge and according to [this](https://github.com/RaRe-Technologies/gensim/issues/449) issue, Gensim has no GPU implementation. So far bnwiki doc2vec model is based on CPU. 
But there might be some alternative third-party tool you check, although I am not sure about it. 
You should check the Gensim issue, you might get some overview and tools.

**Comment by sagorbrur** [comment]
> I am using the bnwiki doc2vec model. It computes embeddings using CPU. It is taking too much time to compute the document embeddings. How can I make it run on my CUDA enabled GPU?

Hi @Codernob ,
I have found the problem. Because we are loading the model every time it takes time for loading. 
I have refactored the code. I will publish soon. Now while initializing the BengaliDoc2vec class you can pass the model and it will load once.
then you can create an instance and call the load model every time you want to generate a document vector.
Hope this might help you. 
Thanks for the issue.
