### ISSUE TITLE
Failed building wheel for gensim

### ISSUE THREAD

**Issue by rahmansean** [sagorbrur/bnlp#29]
When I try to run pip install bnlp_toolkit it gives error of 'Failed building wheel for gensim' and terminates building.
My Os: Google Collab
Python Version: 3.10.11
Added 3 images:
![Main Error](https://user-images.githubusercontent.com/99985100/235224792-a1b2cc58-9301-4473-9cfa-81c9bfd24a58.png)
![Pip Install](https://user-images.githubusercontent.com/99985100/235224800-5282290d-ad22-4b0d-b45b-6066af65fbbf.png)
![Python](https://user-images.githubusercontent.com/99985100/235224808-9318ac76-afc7-4ec7-b895-72d72f8566cc.png)

**Comment by sagorbrur** [comment]
Hi @rahmansean ,
The root cause of this problem is Gensim 4.0.1 version is not compatible with Python 3.10. 
You can downgrade the Python version to 3.9 or 3.8 and try again. I hope it will install successfully.
I will look into this version problem and make bnlp_toolkit compatible with Python 3.10 soon.
Thanks for raising the issue.

**Comment by sagorbrur** [comment]
Hi @rahmansean ,
Released a patch after fixing the Gensim incompatibility problem. 
Check the latest version [3.3.1](https://github.com/sagorbrur/bnlp/releases/tag/v3.3.1)
Please feel free to share if there any problem arise while running this version

**Comment by rahmansean** [comment]
Thank you so much @sagorbrur. It works now.

**Comment by AakashSorathiya** [comment]
Hi @sagorbrur, I am facing the same issue while installing gensim using `pip install gensim`
gensim - 4.3.2
python  - 3.12.1

![image](https://github.com/sagorbrur/bnlp/assets/39656130/581da787-5e65-4a85-8cf5-458783454dc4)
